const String kPostAdmissionsAdmissionidMedications = 'postAdmissionsAdmissionidMedications';
const String kGetAdmissionsAdmissionidMedications = 'getAdmissionsAdmissionidMedications';
const String kPutAdmissionsAdmissionidMedications = 'putAdmissionsAdmissionidMedications';
const String kDeleteAdmissionsAdmissionidMedications = 'deleteAdmissionsAdmissionidMedications';
